spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 539888671564-iov4f5pancvujoec3mt3cpomdia98jov.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile